import { callClaude, type ClaudeTurn, type ClaudeMediaBlock } from './anthropic'
import { extractJson } from './factcheck'
import { readC2paFromBase64, readCameraFromBase64 } from './c2pa'
import { uid, cleanText } from './utils'
import type {
  Asset,
  OriginBand,
  OriginReport,
  OriginSignal,
  Provenance,
  Settings,
} from './types'

const BANDS: OriginBand[] = ['LIKELY_HUMAN', 'LEANS_HUMAN', 'UNCERTAIN', 'LEANS_AI', 'LIKELY_AI']

function bandFromLikelihood(p: number): OriginBand {
  if (p < 0.2) return 'LIKELY_HUMAN'
  if (p < 0.4) return 'LEANS_HUMAN'
  if (p < 0.6) return 'UNCERTAIN'
  if (p < 0.8) return 'LEANS_AI'
  return 'LIKELY_AI'
}

function coerceBand(v: any, p: number): OriginBand {
  const up = String(v ?? '').toUpperCase().replace(/[\s-]+/g, '_')
  return (BANDS as string[]).includes(up) ? (up as OriginBand) : bandFromLikelihood(p)
}

function coercePoints(v: any): 'ai' | 'human' | 'neutral' {
  const t = String(v ?? '').toLowerCase()
  return t === 'ai' || t === 'human' ? t : 'neutral'
}

function num(v: any, lo: number, hi: number, fb: number): number {
  const x = Number(v)
  if (!Number.isFinite(x)) return fb
  return Math.max(lo, Math.min(hi, x))
}

function buildSystem(medium: 'image' | 'text'): string {
  const tellLine =
    medium === 'image'
      ? `For images, weigh tells like: texture coherence, lighting/shadow physics, anatomy (hands, teeth, eyes, ears), background/object consistency, repeated patterns, over-smooth or plasticky surfaces, garbled text in-frame, watermark or generator UI residue, and any embedded provenance metadata you can infer (C2PA, EXIF). Real photos have sensor noise, optical imperfections, and consistent physics; AI images often fail at fine structure and lighting consistency.`
      : `For text, weigh tells like: phrasing uniformity and low burstiness, overly balanced structure, hedging and list-y scaffolding, generic transitions, absence of idiosyncrasy/typos/voice, hollow specificity, and template-like openings/closings. Human writing tends to vary sentence length, take risks, and carry a personal voice; AI text tends to be smooth, even, and safe.`

  return `You are an AI-content origin analyst. You assess whether a piece of content was likely generated by AI or made by a human, and you report your reasoning honestly.

CRITICAL HONESTY RULE: No detector — including you — can know the truth with certainty. Detection is probabilistic and easy to fool (humans write like AI, AI is edited by humans, metadata is stripped, paraphrasers defeat stylometry). Never claim certainty. Express a LIKELIHOOD and show the concrete signals behind it. When evidence is weak or mixed, say so and stay near the middle.

${tellLine}

Definitions:
- aiLikelihood: 0.0 (clearly human-made) to 1.0 (clearly AI-generated). Use the middle (0.4-0.6) when genuinely unsure — do not force a side.
- confidence: how sure you are of your read, 0.0-1.0. Weak/short/ambiguous input → low confidence.
- band: one of LIKELY_HUMAN, LEANS_HUMAN, UNCERTAIN, LEANS_AI, LIKELY_AI.
- signals: 2-6 concrete tells you actually observed. Each has label (short, specific, e.g. "uniform sentence rhythm" or "inconsistent finger count") and points ("ai" | "human" | "neutral"). Include signals on BOTH sides when present — do not cherry-pick.
- rationale: 1-3 sentences, plain language, weighing the evidence and naming the biggest uncertainty.

OUTPUT: Respond with ONLY a single JSON object, no prose, in exactly this shape:
{
  "aiLikelihood": 0.0,
  "confidence": 0.0,
  "band": "UNCERTAIN",
  "signals": [ { "label": "<short>", "points": "ai|human|neutral" } ],
  "rationale": "<short>"
}`
}

export interface OriginResult {
  report: OriginReport | null
  raw: string
  usage?: { input_tokens: number; output_tokens: number }
}

function parse(raw: string, name: string, medium: 'image' | 'text'): OriginReport | null {
  const parsed = extractJson(raw)
  if (!parsed) return null
  const aiLikelihood = num(parsed.aiLikelihood, 0, 1, 0.5)
  const signals: OriginSignal[] = (Array.isArray(parsed.signals) ? parsed.signals : [])
    .filter((s: any) => s && s.label)
    .slice(0, 6)
    .map((s: any) => ({ label: cleanText(String(s.label)), points: coercePoints(s.points) }))
  return {
    id: uid('o'),
    name,
    medium,
    band: coerceBand(parsed.band, aiLikelihood),
    aiLikelihood,
    confidence: num(parsed.confidence, 0, 1, 0.4),
    signals,
    rationale: cleanText(String(parsed.rationale ?? '')),
    createdAt: Date.now(),
  }
}

/** Read verifiable Content Credentials + camera EXIF from an image asset. */
function readProvenance(asset: Asset): Provenance | undefined {
  if (asset.kind !== 'image' || !asset.data) return undefined
  const c2pa = readC2paFromBase64(asset.data)
  const camera = readCameraFromBase64(asset.data)
  if (!c2pa.present && !camera) return undefined
  return {
    hasCredentials: c2pa.present,
    claimsAi: c2pa.aiGenerated,
    generator: c2pa.generator,
    issuer: c2pa.issuer,
    sourceType: c2pa.digitalSourceType,
    camera,
  }
}

/** Build a report driven by verifiable provenance, no model guess needed. */
function provenanceReport(asset: Asset, prov: Provenance): OriginReport {
  const signals: OriginSignal[] = []
  if (prov.hasCredentials) {
    signals.push({
      label: prov.generator
        ? `Content Credentials present (${prov.generator})`
        : 'C2PA Content Credentials present',
      points: prov.claimsAi ? 'ai' : 'neutral',
    })
  }
  if (prov.sourceType)
    signals.push({ label: `Declared source: ${prov.sourceType}`, points: 'ai' })
  if (prov.issuer) signals.push({ label: `Signed by ${prov.issuer}`, points: 'neutral' })
  if (prov.camera) signals.push({ label: `Camera EXIF: ${prov.camera}`, points: 'human' })

  // credentials that claim AI = near-certain; camera-only = leans human
  const aiLikelihood = prov.claimsAi ? 0.97 : prov.hasCredentials ? 0.5 : 0.2
  const band: OriginBand = prov.claimsAi
    ? 'LIKELY_AI'
    : prov.hasCredentials
      ? 'UNCERTAIN'
      : 'LEANS_HUMAN'
  const rationale = prov.claimsAi
    ? `This file carries embedded Content Credentials${prov.generator ? ` from ${prov.generator}` : ''} that declare it AI-generated. Credentials read directly from the file, not inferred.`
    : prov.hasCredentials
      ? 'This file carries Content Credentials, but they do not declare AI generation. The credentials record an edit/provenance history.'
      : `No Content Credentials, but EXIF names a camera${prov.camera ? ` (${prov.camera})` : ''}, which points toward a real capture. Metadata can be edited, so treat as a hint.`

  return {
    id: uid('o'),
    name: asset.name,
    medium: 'image',
    provenance: prov,
    band,
    aiLikelihood,
    confidence: prov.claimsAi ? 0.95 : 0.55,
    signals,
    rationale,
    createdAt: Date.now(),
  }
}

/** Assess whether an uploaded asset (image or document/text) is AI-generated. */
export async function detectAssetOrigin(
  asset: Asset,
  settings: Settings,
  ctx: { signal?: AbortSignal } = {},
): Promise<OriginResult> {
  const medium: 'image' | 'text' = asset.kind === 'image' ? 'image' : 'text'

  // 1) Robust path first: verifiable Content Credentials. When the file says
  //    "I'm AI-generated" cryptographically, we trust that over any model guess.
  const prov = readProvenance(asset)
  if (prov?.claimsAi) {
    return { report: provenanceReport(asset, prov), raw: '[c2pa]' }
  }

  let content = 'Assess the origin of the attached content. Respond with ONLY the JSON object.'
  let media: ClaudeMediaBlock[] | undefined
  if (asset.kind === 'text' && asset.text) {
    content = `Assess whether the following text is AI-generated or human-written. Respond with ONLY the JSON object.\n\n--- ${asset.name} ---\n${asset.text.slice(0, 12000)}`
  } else if (asset.data && (asset.kind === 'image' || asset.kind === 'document')) {
    media = [{ kind: asset.kind, mediaType: asset.mediaType, data: asset.data }]
  }
  const turn: ClaudeTurn = { role: 'user', content, media }

  const result = await callClaude({
    apiKey: settings.apiKey,
    model: settings.model,
    system: buildSystem(medium),
    messages: [turn],
    webSearch: false, // origin read is intrinsic to the content; no grounding
    maxTokens: 1024,
    signal: ctx.signal,
  })

  const report = parse(result.text, asset.name, medium)
  // 2) attach any provenance hints (camera EXIF, non-AI credentials) to the read
  if (report && prov) {
    report.provenance = prov
    if (prov.hasCredentials)
      report.signals.unshift({ label: 'C2PA Content Credentials present', points: 'neutral' })
    if (prov.camera)
      report.signals.unshift({ label: `Camera EXIF: ${prov.camera}`, points: 'human' })
  }
  return { report, raw: result.text, usage: result.usage }
}

/** Assess whether a raw block of text is AI-written (selection / paste). */
export async function detectTextOrigin(
  text: string,
  name: string,
  settings: Settings,
  ctx: { signal?: AbortSignal } = {},
): Promise<OriginResult> {
  const clean = text.trim()
  if (!clean) return { report: null, raw: '' }
  const result = await callClaude({
    apiKey: settings.apiKey,
    model: settings.model,
    system: buildSystem('text'),
    user: `Assess whether the following text is AI-generated or human-written. Respond with ONLY the JSON object.\n\n${clean.slice(0, 12000)}`,
    webSearch: false,
    maxTokens: 1024,
    signal: ctx.signal,
  })
  return { report: parse(result.text, name, 'text'), raw: result.text, usage: result.usage }
}
